version: '3.5'

services:
  jenkis_server:
    image: jenkins/jenkins
    container_name: jenkis_server
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkis_home

volumes:
  jenkins_data:
    name: jenkins_data